export const SERVERS = [
  'US West (Oregon 1)',
  'US West (Oregon 2)',
  'US West (N. California 1)',
  'US West (N. California 2)',
  'US East (N. Virginia 1)',
  'US East (N. Virginia 2)',
  'US Central (Texas)',
  'US Central (Illinois)',
  'US Central (Georgia)',
  'Santiago',
  'Mexico City',
  'Miami',
  'Sao Paulo 1',
  'Sao Paulo 2',
  'Frankfurt 1',
  'Frankfurt 2',
  'Paris 1',
  'Paris 2',
  'Stockholm 1',
  'Stockholm 2',
  'Istanbul',
  'London',
  'Tokyo',
  'Warsaw',
  'Madrid',
  'Bahrain',
  'Seoul 1',
  'Seoul 2',
  'Hong Kong 1',
  'Hong Kong 2',
  'Tokyo 1',
  'Tokyo 2',
  'Singapore 1',
  'Singapore 2',
  'Sydney 1',
  'Sydney 2',
  'Mumbai',
];
